version: "3"
   
services:
    django:
        build: .
        container_name: django
        command: >
          sh -c " python manage.py makemigrations &&
                  python manage.py migrate &&
                  python manage.py runserver 0.0.0.0:8800"
        environment:
          - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0

        volumes:
            - .:/youtube/app/
        env_file:
          - youtube/.env
        ports:
            - "8800:8800"
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A youtube worker -l INFO
        environment:
          - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0

        volumes:
            - .:/youtube/app/
        env_file:
          - youtube/.env
        depends_on:
            - django
            - redis
    celery-beat:
        build: .
        command: celery -A youtube beat -l info
        volumes:
          - .:/youtube/app/
        environment:
          - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
          - django
          - celery
          - redis
    redis:
        image: "redis:alpine"
        ports:
          - "6379:6379"
